import { useEffect, useState, type FormEvent } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { getOrganizationApplication, submitOrganizationApplication, submitWeeklyNeeds, type OrganizationApplication } from '../services/api'

const produce = ['Tomatoes', 'Cucumbers', 'Zucchini', 'Kale', 'Spinach', 'Peppers', 'Carrots', 'Herbs']
const nextSaturday = () => { const d = new Date(); d.setDate(d.getDate() + ((6 - d.getDay() + 7) % 7 || 7)); return d.toISOString().slice(0, 10) }

export function OrganizationPage() {
  const { user } = useAuth(); const [application, setApplication] = useState<OrganizationApplication | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { if (user?.role === 'organization') getOrganizationApplication().then(setApplication).catch((e) => setError(e.message)).finally(() => setLoading(false)) }, [user])
  if (!user) return <Navigate to="/auth?returnTo=/organization" replace />
  if (user.role !== 'organization') return <div className="page container empty-state"><h1>Organization account required</h1><Link className="button button-dark" to="/account">Switch account</Link></div>
  if (loading) return <div className="page container"><p>Loading organization workspace…</p></div>
  const apply = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const d = new FormData(event.currentTarget); try { setApplication(await submitOrganizationApplication({ organization_name: String(d.get('organization_name')), organization_type: String(d.get('organization_type')), address: String(d.get('address')), borough: String(d.get('borough')), neighborhood: String(d.get('neighborhood')), contact_name: String(d.get('contact_name')), phone: String(d.get('phone')), accepted_categories: d.getAll('accepted_categories').map(String), opening_time: String(d.get('opening_time')), closing_time: String(d.get('closing_time')), notes: String(d.get('notes')) })); setMessage('Application submitted for review.') } catch (e) { setError(e instanceof Error ? e.message : 'Could not submit application.') } }
  const saveNeeds = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const d = new FormData(event.currentTarget); const items = produce.map((name) => ({ produce_name: name.toLowerCase(), need_level: String(d.get(`${name}-level`)), requested_quantity: Number(d.get(`${name}-quantity`)) || 0 })).filter((item) => item.need_level !== 'none'); try { await submitWeeklyNeeds({ distribution_date: String(d.get('distribution_date')), accepting_donations: d.get('accepting_donations') === 'on', dropoff_start: String(d.get('dropoff_start')), dropoff_end: String(d.get('dropoff_end')), notes: String(d.get('notes')), items: items.length ? items : [{ produce_name: 'none', need_level: 'none', requested_quantity: 0 }] }); setMessage('Weekly needs published. Matching now uses this update.') } catch (e) { setError(e instanceof Error ? e.message : 'Could not publish needs.') } }
  return <div className="page container organization-page"><div className="page-title"><span className="kicker">ORGANIZATION PORTAL</span><h1>{application?.organization_name || 'Join the network'}</h1><p>Verified partners publish what they can accept, so gardeners arrive with useful produce at the right time.</p></div>{error && <p className="workflow-error" role="alert">{error}</p>}{message && <p className="form-message" role="status">{message}</p>}
    {!application && <section className="workflow-card"><h2>Organization application</h2><p>NeedYield reviews every organization before it appears as a donation destination.</p><form className="organization-form" onSubmit={apply}><label>Name<input name="organization_name" required /></label><label>Type<select name="organization_type"><option>Food pantry</option><option>Community fridge</option><option>Community organization</option><option>Mutual aid group</option></select></label><label className="wide">Street address<input name="address" required /></label><label>Borough<select name="borough"><option>Manhattan</option><option>Bronx</option><option>Brooklyn</option><option>Queens</option><option>Staten Island</option></select></label><label>Neighborhood<input name="neighborhood" required /></label><label>Primary contact<input name="contact_name" required /></label><label>Phone<input name="phone" type="tel" required /></label><label>Donation window starts<input name="opening_time" type="time" required /></label><label>Donation window ends<input name="closing_time" type="time" required /></label><fieldset className="wide"><legend>Accepted categories</legend><div className="check-row">{['vegetables', 'fruit', 'herbs'].map((item) => <label key={item}><input type="checkbox" name="accepted_categories" value={item} defaultChecked /> {item}</label>)}</div></fieldset><label className="wide">Storage, access, or donation notes<textarea name="notes" rows={3} /></label><button className="button button-dark">Submit for verification</button></form></section>}
    {application?.status === 'PENDING' && <section className="status-panel"><span className="status status-reserved">PENDING REVIEW</span><h2>Your application is in the approval queue.</h2><p>NeedYield verifies the organization and its map coordinates before gardeners can be directed here.</p></section>}
    {application?.status === 'REJECTED' && <section className="status-panel"><span className="status status-expired">NEEDS ATTENTION</span><h2>We need more information.</h2><p>{application.review_note}</p></section>}
    {application?.status === 'APPROVED' && <section className="workflow-card"><span className="status status-reserved">VERIFIED ORGANIZATION</span><h2>One-minute weekly needs update</h2><p>This explicit need is prioritized in gardener matching.</p><form className="organization-form" onSubmit={saveNeeds}><label>Distribution date<input name="distribution_date" type="date" required defaultValue={nextSaturday()} /></label><label className="checkbox-card"><input name="accepting_donations" type="checkbox" defaultChecked /> Accepting donations this week</label><label>Drop-off starts<input name="dropoff_start" type="time" required defaultValue="09:00" /></label><label>Drop-off ends<input name="dropoff_end" type="time" required defaultValue="17:00" /></label><div className="need-grid wide"><strong>Produce</strong><strong>Need</strong><strong>Quantity</strong>{produce.map((name) => <div className="need-row" key={name}><span>{name}</span><select name={`${name}-level`} defaultValue="none"><option value="none">No need</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select><input aria-label={`${name} quantity`} name={`${name}-quantity`} type="number" min="0" defaultValue="0" /></div>)}</div><label className="wide">Notes<textarea name="notes" rows={3} /></label><button className="button button-dark">Publish weekly needs</button></form></section>}
  </div>
}
